---
- name: Execute create_temp_folder role
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
          - local
          #- remote


# - name: Execute copy_files_to_dev_env role
#   hosts: dev_env
#   become: yes
#   gather_facts: true
#   roles:
#     - Ansible/remote/task/main.yml
#     - Ansible/vars/main.yml
