---
- name: Execute create_temp_folder role
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - local/task/main.yml
    - vars/main.yml
- name: Execute copy_files_to_dev_env role
  hosts: dev_env
  become: yes
  gather_facts: true
  roles:
    - remote/task/main.yml
    - vars/main.yml
